<a href="https://colab.research.google.com/github/192524115simats-hub/ITA0604-slot_C/blob/main/machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data=pd.read_csv("enjoysport.csv")
print(data)

     Sky AirTemp Humidity    Wind Water Forecast EnjoySport
0  Sunny    Warm   Normal  Strong  Warm     Same        Yes
1  Sunny    Warm     High  Strong  Warm     Same        Yes
2  Rainy    Cold     High  Strong  Warm   Change         No
3  Sunny    Warm     High  Strong  Cool   Change        Yes


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Large model may memorize a small dataset
model = Sequential([
    Dense(128, activation="relu", input_shape=(10,)),
    Dense(128, activation="relu"),
    Dense(1, activation="sigmoid")
])

print("Problem: Large model may cause overfitting.")

Problem: Large model may cause overfitting.


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential([
    Dense(128, activation="relu", input_shape=(10,)),
    Dropout(0.5),       # Temporarily switches off 50% neurons

    Dense(64, activation="relu"),
    Dropout(0.3),

    Dense(1, activation="sigmoid")
])

print("Solution: Dropout reduces overfitting.")

Solution: Dropout reduces overfitting.


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Very small model
model = Sequential([
    Dense(1, activation="sigmoid", input_shape=(10,))
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

print("Problem: Model is too small and may underfit.")

# Solution
model = Sequential([
    Dense(64, activation="relu", input_shape=(10,)),
    Dense(32, activation="relu"),
    Dense(1, activation="sigmoid")
])
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

print("Solution: Use more neurons, layers and training epochs.")


Problem: Model is too small and may underfit.
Solution: Use more neurons, layers and training epochs.


In [ ]:
import numpy as np
# Input values
x = np.array([-3, -2, -1, 0, 1, 2, 3])
# Apply Tanh activation function
output = np.tanh(x)
print("Input Values:")
print(x)
print("\nTanh Output:")
print(output)

import numpy as np
# Input values
x = np.array([-5, -2, 0, 3, 7])
# Apply ReLU activation function
relu_output = np.maximum(0, x)
print("Input Values:")
print(x)
print("\nReLU Output:")
print(relu_output)

import numpy as np
marks = np.array([-10, 20, 50, -30, 80])
relu_marks = np.maximum(0, marks)
print("Original Marks :", marks)
print("After ReLU     :", relu_marks)

import numpy as np
# Input values
x = np.array([-5, -2, 0, 2, 5])
# Apply Sigmoid activation function
sigmoid_output = 1 / (1 + np.exp(-x))
print("Input Values:")
print(x)
print("\nSigmoid Output:")
print(sigmoid_output)


import numpy as np
marks = np.array([85, 70, 60])
softmax = np.exp(marks) / np.sum(np.exp(marks))
print("Scores :", marks)
print("Softmax:", softmax)

Input Values:
[-3 -2 -1  0  1  2  3]

Tanh Output:
[-0.99505475 -0.96402758 -0.76159416  0.          0.76159416  0.96402758
  0.99505475]
Input Values:
[-5 -2  0  3  7]

ReLU Output:
[0 0 0 3 7]
Original Marks : [-10  20  50 -30  80]
After ReLU     : [ 0 20 50  0 80]
Input Values:
[-5 -2  0  2  5]

Sigmoid Output:
[0.00669285 0.11920292 0.5        0.88079708 0.99330715]
Scores : [85 70 60]
Softmax: [9.99999694e-01 3.05902227e-07 1.38879396e-11]


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
import numpy as np

X = np.array([[0,0], [0,1], [1,0], [1,1]], dtype=float)
Y = np.array([0, 0, 0, 1], dtype=float)

# Modern Keras setup using an explicit Input layer
perceptron = Sequential([
    Input(shape=(2,)),
    Dense(1, activation="sigmoid")
])

perceptron.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
perceptron.fit(X, Y, epochs=10, verbose=0)

perceptron.summary()


Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_20 (Dense)                │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11 (48.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 8 (36.00 B)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

# Assuming your input data has 10 features
model = Sequential([
    # 1. Define the input shape explicitly
    Input(shape=(10,)),

    # 2. First Hidden Layer (Extracts initial patterns)
    Dense(128, activation="relu"),

    # 3. Second Hidden Layer (Combines patterns into deeper features)
    Dense(64, activation="relu"),

    # 4. Third Hidden Layer (Fine-tunes the features)
    Dense(32, activation="relu"),

    # 5. Output Layer (1 neuron for binary prediction: 0 or 1)
    Dense(1, activation="sigmoid")
])

# Compile the model
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Print a breakdown of the total layers and parameters
model.summary()


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_16 (Dense)                │ (None, 128)            │         1,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,777 (46.00 KB)

 Trainable params: 11,777 (46.00 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# 1. Import necessary libraries
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# 2. Load the simple dataset
# We use the standard Iris flowers dataset (150 samples, 4 features)
iris = load_iris()
X = iris.data
y = iris.target

# 3. Split data into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 4. Standardize the features for better neural network convergence
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 5. Initialize and train the Single-Layer Perceptron
perceptron_model = Perceptron(max_iter=1000, random_state=42)
perceptron_model.fit(X_train, y_train)

# 6. Initialize and train the Multi-Layer Perceptron (MLP)
# This includes 1 hidden layer with 10 hidden neurons
mlp_model = MLPClassifier(hidden_layer_sizes=(10,), max_iter=1000, random_state=42)
mlp_model.fit(X_train, y_train)

# 7. Make predictions on the test set
y_pred_perceptron = perceptron_model.predict(X_test)
y_pred_mlp = mlp_model.predict(X_test)

# 8. Calculate and print the accuracies
accuracy_perceptron = accuracy_score(y_test, y_pred_perceptron)
accuracy_mlp = accuracy_score(y_test, y_pred_mlp)

print("--- Accuracy Comparison ---")
print(f"Single-Layer Perceptron Accuracy : {accuracy_perceptron * 100:.2f}%")
print(f"Multi-Layer Perceptron Accuracy  : {accuracy_mlp * 100:.2f}%")


--- Accuracy Comparison ---
Single-Layer Perceptron Accuracy : 93.33%
Multi-Layer Perceptron Accuracy  : 100.00%
